name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feature suggestion! Please fill out the form below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - ACN Core Service
        - TypeScript SDK (@acn/client)
        - Python SDK (acn-client)
        - API
        - Docker/Deployment
        - Documentation
        - New SDK (Go, Rust, etc.)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be implemented?
      placeholder: |
        I think we should...
        
        Example API:
        ```python
        client.new_method()
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I would be willing to implement this feature
































