"""restore_participations_task_fk

Revision ID: 1e400bcfd4ec
Revises: 7ee2ed3a177c
Create Date: 2026-03-17 14:13:48.121802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e400bcfd4ec'
down_revision: Union[str, Sequence[str], None] = '7ee2ed3a177c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'participations', 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participations', type_='foreignkey')
    # ### end Alembic commands ###
