"""expand_verification_code_to_64chars

Revision ID: 7ee2ed3a177c
Revises: a1b2c3d4e5f6
Create Date: 2026-03-17 12:30:35.971476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ee2ed3a177c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverables_agent_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_deliverable_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_task_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.alter_column('agents', 'verification_code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('ix_agents_skills'), table_name='agents', postgresql_using='gin')
    op.create_index('ix_agents_tags', 'agents', ['skills'], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('participations_task_id_fkey'), 'participations', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('participations_task_id_fkey'), 'participations', 'tasks', ['task_id'], ['task_id'], ondelete='CASCADE')
    op.drop_index('ix_agents_tags', table_name='agents', postgresql_using='gin')
    op.create_index(op.f('ix_agents_skills'), 'agents', ['skills'], unique=False, postgresql_using='gin')
    op.alter_column('agents', 'verification_code',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.create_table('deliverables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('deliverable_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('storage_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('git_commit_sha', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('git_file_paths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('git_branch', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('pr_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pr_merged', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('s3_file_keys', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('s3_total_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shadow_doc_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('preview_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('review_comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('deliverables_task_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deliverables_pkey'))
    )
    op.create_index(op.f('ix_deliverables_task_id'), 'deliverables', ['task_id'], unique=False)
    op.create_index(op.f('ix_deliverables_id'), 'deliverables', ['id'], unique=False)
    op.create_index(op.f('ix_deliverables_deliverable_id'), 'deliverables', ['deliverable_id'], unique=True)
    op.create_index(op.f('ix_deliverables_agent_id'), 'deliverables', ['agent_id'], unique=False)
    # ### end Alembic commands ###
